### ISSUE TITLE
Add Neural networks code from scratch in C++

### ISSUE THREAD

**Issue by extinctsion** [extinctsion/neuralNetworkScratch#14]
Add neural network code from scratch using C++
[Hint]: You can take help from the python code. Your code should do the same thing as neuralNetwork0.py in cpp

**Comment by tejasrok007** [comment]
can assign this to me i will create a pull request for this?
![image](https://github.com/user-attachments/assets/94067bb5-d8cc-4834-87f7-9046c278baaf)

**Comment by extinctsion** [comment]
Ok. sure.

**Comment by extinctsion** [comment]
Also can you add a step in workflow to test ur code using some tool and then you will be able to merge the code? If would be great. Same for Java.
